---
- name: Analysis
  hosts: "{{ ripu_pet_name is defined | ternary( ripu_pet_name, rhel_inventory_group | default(omit) ) }}"
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  pre_tasks:
    - name: Register output of 'yum repolist'
      ansible.builtin.shell: |
        set -o pipefail
        yum repolist
      args:
        executable: /bin/bash
      register: yum_repolist
      changed_when: yum_repolist.rc != 0

    # Determine if node is an EC2 Marketplace instance utilzing RHUI
    - name: Set fact for RHUI RHEL extras repo name when EC2 and utilizing RHUI
      ansible.builtin.set_fact:
        analysis_repos_el7: "rhel-7-server-rhui-extras-rpms"
      when:
        - ansible_system_vendor == "Amazon EC2" or ansible_system_vendor == "Xen"
        - ansible_product_uuid|regex_search('^ec2') or ansible_product_uuid|regex_search('^EC2')
        - "'rhui' in yum_repolist.stdout"
        - ansible_distribution_major_version|int == 7

    - name: Set analysis package list facts for preupgrade analysis for RHUI Marketplace Leapp upgrades
      ansible.builtin.set_fact:
        analysis_packages_el7:
          - leapp-rhui-aws
          - cockpit
          - cockpit-system
          - cockpit-leapp
        analysis_packages_el8:
          - leapp-rhui-aws
          - leapp-upgrade
          - cockpit
          - cockpit-system
          - cockpit-leapp
      when:
        - ansible_system_vendor == "Amazon EC2" or ansible_system_vendor == "Xen"
        - ansible_product_uuid|regex_search('^ec2') or ansible_product_uuid|regex_search('^EC2')
        - "'rhui' in yum_repolist.stdout"
  ansible.builtin.import_role:
    - infra.leapp.analysis
...
